#### PTID-CDS-JUN-26-11194

#### Task 1: Prepare a complete data analysis report on the given data

In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("train(1).csv")

In [3]:
data

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,train_199995,0,11.4880,-0.4956,8.2622,3.5142,10.3404,11.6081,5.6709,15.1516,...,6.1415,13.2305,3.9901,0.9388,18.0249,-1.7939,2.1661,8.5326,16.6660,-17.8661
199996,train_199996,0,4.9149,-2.4484,16.7052,6.6345,8.3096,-10.5628,5.8802,21.5940,...,4.9611,4.6549,0.6998,1.8341,22.2717,1.7337,-2.1651,6.7419,15.9054,0.3388
199997,train_199997,0,11.2232,-5.0518,10.5127,5.6456,9.3410,-5.4086,4.5555,21.5571,...,4.0651,5.4414,3.1032,4.8793,23.5311,-1.5736,1.2832,8.7155,13.8329,4.1995
199998,train_199998,0,9.7148,-8.6098,13.6104,5.7930,12.5173,0.5339,6.0479,17.0152,...,2.6840,8.6587,2.7337,11.1178,20.4158,-0.0786,6.7980,10.0342,15.5289,-13.9001
199999,train_199999,0,10.8762,-5.7105,12.1183,8.0328,11.5577,0.3488,5.2839,15.2058,...,8.9842,1.6893,0.1276,0.3766,15.2101,-2.4907,-2.2342,8.1857,12.1284,0.1385

In [4]:
data.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Columns: 202 entries, ID_code to var_199
dtypes: float64(200), int64(1), object(1)
memory usage: 308.2+ MB

In [6]:
data.describe()

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,0.100490,10.679914,-1.627622,10.715192,6.796529,11.078333,-5.065317,5.408949,16.545850,0.284162,...,3.234440,7.438408,1.927839,3.331774,17.993784,-0.142088,2.303335,8.908158,15.870720,-3.326537
std,0.300653,3.040051,4.050044,2.640894,2.043319,1.623150,7.863267,0.866607,3.418076,3.332634,...,4.559922,3.023272,1.478423,3.992030,3.135162,1.429372,5.454369,0.921625,3.010945,10.438015
min,0.000000,0.408400,-15.043400,2.117100,-0.040200,5.074800,-32.562600,2.347300,5.349700,-10.505500,...,-14.093300,-2.691700,-3.814500,-11.783400,8.694400,-5.261000,-14.209600,5.960600,6.299300,-38.852800
25%,0.000000,8.453850,-4.740025,8.722475,5.254075,9.883175,-11.200350,4.767700,13.943800,-2.317800,...,-0.058825,5.157400,0.889775,0.584600,15.629800,-1.170700,-1.946925,8.252800,13.829700,-11.208475
50%,0.000000,10.524750,-1.608050,10.580000,6.825000,11.108250,-4.833150,5.385100,16.456800,0.393700,...,3.203600,7.347750,1.901300,3.396350,17.957950,-0.172700,2.408900,8.888200,15.934050,-2.819550
75%,0.000000,12.758200,1.358625,12.516700,8.324100,12.261125,0.924800,6.003000,19.102900,2.937900,...,6.406200,9.512525,2.949500,6.205800,20.396525,0.829600,6.556725,9.593300,18.064725,4.836800
max,1.000000,20.315000,10.376800,19.353000,13.188300,16.671400,17.251600,8.447700,27.691800,10.151300,...,18.440900,16.716500,8.402400,18.281800,27.928800,4.272900,18.321500,12.000400,26.079100,28.500700

In [7]:
data.shape

(200000, 202)

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.isnull().sum()

ID_code    0
target     0
var_0      0
var_1      0
var_2      0
          ..
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 202, dtype: int64

In [10]:
data["target"].value_counts()

target
0    179902
1     20098
Name: count, dtype: int64

#### 1)The dataset contains Customer transaction information 200 feature , one  ID_code column , and one traget column .
#### 2)The shape of dataset Rows : 200000 , Column : 202
#### 3)All predictor variables are in numerical in nature 
#### 4)No missing values and duplicate Values were found in the given dataset
#### 5)The dataset is imbalanced ,as the number of transactions (target=1) is lower than the number of customers not making transactions(target=0)
#### 6)The dataset suitable for building classification models

#### Task 2 : Create a predictive model which will help the bank to identify which customer will make transactions in future

In [11]:
X=data.drop(["ID_code","target"],axis=1)

In [12]:
X.head()

,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,-4.9200,5.7470,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,3.1468,8.0851,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,-4.9193,5.9525,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,-5.8609,8.2450,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,6.2654,7.6784,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [13]:
y=data["target"]

In [14]:
y

0         0
1         0
2         0
3         0
4         0
         ..
199995    0
199996    0
199997    0
199998    0
199999    0
Name: target, Length: 200000, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
sd=StandardScaler()
X_train=sd.fit_transform(X_train)
X_test=sd.transform(X_test)

#### Logistic Regression

In [17]:
import warnings
warnings.filterwarnings('ignore') 
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(class_weight="balanced",max_iter=1000)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,f1_score,recall_score,roc_auc_score
print("Confusion matrix :",confusion_matrix(y_test,y_pred))
print("Accuracy :",accuracy_score(y_test,y_pred))
print("precision score :",precision_score(y_test,y_pred))
print("recall score :",recall_score(y_test,y_pred))
print("f1_score :",f1_score(y_test,y_pred))

Confusion matrix : [[28219  7761]
 [  903  3117]]
Accuracy : 0.7834
precision score : 0.2865416436845008
recall score : 0.7753731343283582
f1_score : 0.4184454289166331

In [19]:
y_prob = model.predict_proba(X_test)[:,1]
auc = roc_auc_score(y_test, y_prob)
print("AUC :", auc)

AUC : 0.8598998891036755

### KNN Classifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for k in range(1,21):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    pred=knn.predict(X_test)
    acc_score=accuracy_score(y_test,pred)
    print("K :",k ,"ACC :",acc_score)

K : 1 ACC : 0.88295
K : 2 ACC : 0.899275
K : 3 ACC : 0.898275
K : 4 ACC : 0.899375
K : 5 ACC : 0.899275
K : 6 ACC : 0.8995
K : 7 ACC : 0.899475
K : 8 ACC : 0.8995
K : 9 ACC : 0.8995
K : 10 ACC : 0.8995
K : 11 ACC : 0.8995
K : 12 ACC : 0.8995
K : 13 ACC : 0.8995
K : 14 ACC : 0.8995
K : 15 ACC : 0.8995
K : 16 ACC : 0.8995
K : 17 ACC : 0.8995
K : 18 ACC : 0.8995
K : 19 ACC : 0.8995
K : 20 ACC : 0.8995

In [21]:
from sklearn.neighbors import KNeighborsClassifier
Knn=KNeighborsClassifier(n_neighbors=7)
Knn.fit(X_train,y_train)
y_kpred=Knn.predict(X_test)

In [22]:
from sklearn.metrics import *
print("Confusion matrix",confusion_matrix(y_test,y_kpred))
print("Accuracy :",accuracy_score(y_test,y_kpred))
print("Precision score :",precision_score(y_test,y_kpred))
print("recall score :",recall_score(y_test,y_kpred))
print("F1_score :",f1_score(y_test,y_kpred))

Confusion matrix [[35979     1]
 [ 4020     0]]
Accuracy : 0.899475
Precision score : 0.0
recall score : 0.0
F1_score : 0.0

In [23]:
from sklearn.metrics import roc_auc_score
y_prob1 = Knn.predict_proba(X_test)[:,1]
print("AUC :", roc_auc_score(y_test, y_prob1))

AUC : 0.5587117739540209

### Decsion Tree Classifier

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(max_depth=10,class_weight='balanced',
    random_state=42)
dtree.fit(X_train,y_train)
y_dpred=dtree.predict(X_test)

In [25]:
from sklearn.metrics import *
print("Confusion Matrix:",confusion_matrix(y_test, y_dpred))
print("Accuracy :", accuracy_score(y_test, y_dpred))
print("Precision :", precision_score(y_test, y_dpred))
print("Recall :", recall_score(y_test, y_dpred))
print("F1 Score :", f1_score(y_test, y_dpred))
y_prob2 = dtree.predict_proba(X_test)[:,1]
print("AUC :", roc_auc_score(y_test, y_prob2))

Confusion Matrix: [[27240  8740]
 [ 2172  1848]]
Accuracy : 0.7272
Precision : 0.17453721193804306
Recall : 0.4597014925373134
F1 Score : 0.25301204819277107
AUC : 0.6331701069416675

### Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rmodel = RandomForestClassifier(class_weight='balanced',
    n_estimators=20,
    random_state=42,
    n_jobs=-1
)
rmodel.fit(X_train, y_train)
y_rpred = rmodel.predict(X_test)

In [ ]:
from sklearn.metrics import *
print("Confusion Matrix:",confusion_matrix(y_test, y_rpred))
print("Accuracy :", accuracy_score(y_test, y_rpred))
print("Precision :", precision_score(y_test, y_rpred))
print("Recall :", recall_score(y_test, y_rpred))
print("F1 Score :", f1_score(y_test, y_rpred))
y_prob3 = rmodel.predict_proba(X_test)[:,1]
print("AUC :", roc_auc_score(y_test, y_prob3))

#### XG Boost

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    scale_pos_weight=9,
    random_state=42
)
xgb.fit(X_train, y_train)
pred_xgb = xgb.predict(X_test)

In [ ]:
from sklearn.metrics import *
print("Confusion Matrix:\n", confusion_matrix(y_test,pred_xgb))
print("Accuracy :", accuracy_score(y_test,pred_xgb))
print("Precision :", precision_score(y_test,pred_xgb))
print("Recall :", recall_score(y_test,pred_xgb))
print("F1 Score :", f1_score(y_test,pred_xgb))
y_prob5 = xgb.predict_proba(X_test)[:,1]
print("AUC :", roc_auc_score(y_test,y_prob5))

#### Comparsion Table

In [ ]:
import pandas as pd
comparison = {
    "Model":     ["XGBoost","Logistic Regression","Decision Tree","Random Forest","KNN"],
    "Accuracy":  [0.8432, 0.7834, 0.7272, 0.8995, 0.8994],
    "Precision": [0.3494, 0.2865, 0.1745, 1.0000, 0.0000],
    "Recall":    [0.6495, 0.7753, 0.4597, 0.0004, 0.0000],
    "F1 Score":  [0.4544, 0.4184, 0.2530, 0.0009, 0.0000],
    "AUC":       [0.8511, 0.8598, 0.6331, 0.6778, 0.5587],
}
df = pd.DataFrame(comparison)
print(df.to_string(index=False))
print("\nBest Model for Production : XGBoost")
print("Reason : Highest F1 Score (45.44%) — best overall balanced performance")
print("Strong AUC (85.11%) and good Recall (64.95%)")
print("Industry standard for large structured banking datasets")

#### Challenges Faced and Techniques Used

#### Challenge 1 — Class Imbalance
Problem  : 90% class 0, 10% class 1. KNN=0 caught, RF=2 caught.
Technique: class_weight='balanced' for LR, DT, RF.
            scale_pos_weight=9 for XGBoost.
#### Challenge 2 — Accuracy is Misleading
Problem  : KNN/RF showed 89% accuracy but F1=0%. Predicted all as class 0.
Technique: Used AUC, Recall, F1 as primary metrics.
#### Challenge 3 — Anonymous Features
Problem  : 200 features named var_0 to var_199. No domain knowledge.
Technique: StandardScaler applied equally to all 200 features.
#### Challenge 4 — Large Dataset
Problem  : 200,000 rows × 200 features. Heavy computation.
Technique: n_jobs=-1 for parallel processing.
#### Best Model for Production — XGBoost
F1    : 45.44%  (highest — best overall balance)
AUC   : 85.11%  (strong discriminating ability)
Recall: 64.95%  (catches 2,611 out of 4,020 transacting customers)
Reason: Best F1 Score + industry standard for banking tabular data.